version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3333:3333'
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/semanaomnistack7
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3333
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: 